// https://en.wikipedia.org/wiki/List_of_languages_by_total_number_of_speakers

module.exports.languageToCode = {
    'Arabic': 'ar',
    'Bengali/Bangla': 'bn',
    'Chinese (Simplified)': 'zh-Hans',
    'Chinese (Traditional)': 'zh-Hant',
    'English': 'en',
    'French': 'fr',
    'German': 'de',
    'Gujarati': 'gu',
    'Hausa': 'ha',
    'Hindi': 'hi',
    'Indonesian': 'in',
    'Italian': 'it',
    'Japanese': 'ja',
    'Javanese': 'jw',
    'Kannada': 'kn',
    'Korean': 'ko',
    'Marathi': 'mr',
    'Persian': 'fa',
    'Portuguese': 'pt',
    'Punjabi': 'pa',
    'Russian': 'ru',
    'Spanish': 'es',
    'Swahili': 'sw',
    'Tamil': 'ta',
    'Telugu': 'te',
    'Thai': 'th',
    'Turkish': 'tr',
    'Urdu': 'ur',
    'Vietnamese': 'vi'
};

module.exports.codeToLanguage = {
    "ar": 'Arabic',
    "bn": 'Bengali/Bangla',
    "zh-Hans": 'Chinese (Simplified)',
    "zh-Hant": 'Chinese (Traditional)',
    "en": 'English',
    "fr": 'French',
    "de": 'German',
    "gu": 'Gujarati',
    "ha": 'Hausa',
    "hi": 'Hindi',
    "in": 'Indonesian',
    "it": 'Italian',
    "ja": 'Japanese',
    "jw": 'Javanese',
    "kn": 'Kannada',
    "ko": 'Korean',
    "mr": 'Marathi',
    "fa": 'Persian',
    "pt": 'Portuguese',
    "pa": 'Punjabi',
    "ru": 'Russian',
    "es": 'Spanish',
    "sw": 'Swahili',
    "ta": 'Tamil',
    "te": 'Telugu',
    "th": 'Thai',
    "tr": 'Turkish',
    "ur": 'Urdu',
    "vi": 'Vietnamese'
};